### PR TITLE
Command/39 `checkPostExists` from any CPT

### LINKED ISSUE #38: Migrate custom commands from 10up/publisher-media-kit
### Is your enhancement related to a problem? Please describe.

- [x] #39
- [x] #40

### Designs

_No response_

### Describe alternatives you've considered

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #39: `checkPostExists` from any CPT
### Is your enhancement related to a problem? Please describe.

Inspired by PMK [test](https://github.com/10up/publisher-media-kit/blob/develop/tests/cypress/integration/pmk-media-kit-page-creation.test.js).

Ability to check a post's existence from any post type.

### Designs

_No response_

### Describe alternatives you've considered

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by faisal-alvi**
### Description of the Change

Added a new command `checkPostExists` which checks whether a given post title exists in a specified post type or not.

It accepts the following parameters.
- `title`: Post Title.
- `postType`: Post type. Default to `post`.

Note: The command searches for the exact `title` on the site. It fails the test if the title string does not match.

Closes #39

### Verification Process

1. Build the project using `npm run build`.
2. Make sure the docker is running.
3. Run `npm run env:start`.
4. Run `npm run cypress:open`.
5. Run `check-post-exists.test.js`.
6. Try to change the post title(s) in the `/tests/cypress/integration/check-post-exists.test.js` file and see the test should fail.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests passed.

### Changelog Entry

> Added - New Command `checkPostExists` to check if post exists.

### Credits

Props @faisal-alvi

### CODE REVIEW

**Review by Sidsector9 — APPROVED** [review]
LGTM 🚀

**Comment by cadic** [comment]
Potentially chainable command. IMO, we should wrap the result and don't fail if the post doesn't exist.

**Comment by Sidsector9** [comment]
@faisal-alvi I have a suggestion to make this command run faster, effectively running tests faster.

The admin page exposes the `wp-json/wp/v2/posts` endpoint which we can use to search for a post(s).
Instead of typing the search term in the search box, submitting and waiting for thee page to reload, we can use REST to search faster:

```JS
fetch( `${Cypress.config().baseUrl}/wp-json/wp/v2/post?s="${searchString}"` )
    .then( response => {
        return response.json();
    } )
    .then( data => {
        // Run assertions here.
    } );
```

Let me know what you think of this. Thanks!

**Comment by faisal-alvi** [comment]
@Sidsector9 thanks for the suggestion, however, I can see only one drawback of using the REST API. It won't work with the CPTs in which the [REST API support](https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-rest-api-support-for-custom-content-types/) is disabled, i.e. `show_in_rest` is set to `false`.

**Comment by faisal-alvi** [comment]
@cadic thanks for the suggestion, the result is now wrapped and returned.

**Comment by Sidsector9** [comment]
Fair point @faisal-alvi

Although, we can still have the best of both worlds:

1. Check via REST.
2. If REST is disabled for a CPT, then use UI

**Comment by cadic** [comment]
@faisal-alvi thank you for the command. I've added few tests to cover the functionality in both situations (post exists or not)

**Comment by faisal-alvi** [comment]
@cadic any thoughts on @Sidsector9's ^recommendation?

**Pull request merged**
