### PR TITLE
Repair E2E tests

### LINKED ISSUE #78: Fix broken tests related to openDocumentSettingsPanel
Some tests fail on WordPress core >= 6.1 after the main panel in the sidebar was renamed to "Summary".

### PR DESCRIPTION
**Pull request by kmgalanakis**
### Description of the Change

Closes https://github.com/10up/cypress-wp-utils/issues/78

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @username, @username2, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Comment by kmgalanakis** [comment]
@jeffpaul I don't know if I should specifically ping you about this.

I managed to fix the E2E tests by ignoring a CORS related error and by running them on Chrome (they were failing on Electron, objections?) but now I'm facing another test failure with WP trunk version. I consistently get an error like

```
Uncaught TypeError: Cannot destructure property 'documentElement' of 'contentDocument' as it is null.
    at HTMLIFrameElement.onLoad (block-editor.js?ver=35750e8f523ab571a7d8:25172:9)
```

when opening the editor using Cypress, something I don't get when loading the exact same site using my Chrome.

I don't know how to proceed, any suggestions?

**Comment by iamdharmesh** [comment]
Hi @kmgalanakis, 

Thank you for the PR.

> I managed to fix the E2E tests by ignoring a CORS related error and by running them on Chrome (they were failing on Electron, objections?) but now I'm facing another test failure with WP trunk version. I consistently get an error like
>```
>Uncaught TypeError: Cannot destructure property 'documentElement' of 'contentDocument' as it is null.
>    at HTMLIFrameElement.onLoad (block-editor.js?ver=35750e8f523ab571a7d8:25172:9)
>```

This is a known issue with WP 6.3 and we have an open issue for it https://github.com/10up/cypress-wp-utils/issues/104. It should be fixed separately from this PR. So, we can proceed here with ignoring it.

Thanks.
cc: @jeffpaul

**Comment by dkotter** [comment]
I'm not sure this is needed anymore after the work that got merged in #105. I ran our E2E tests against every version of WordPress from 5.7 onwards and I don't see any failing tests anymore.

**Comment by iamdharmesh** [comment]
@dkotter I have verified the changes of this PR and it looks like we are good to close this PR and issue.

@kmgalanakis Please feel free to reopen this if you are still facing the reported issue and we misunderstood anything here.

Thank you

**Pull request closed without merging**
