### PR TITLE
fix: try to click on first button that contains text while opening setting sidbar

### PR DESCRIPTION
**Pull request by aliaghdam**
sometimes there are other buttons that contains same text and cypress returns multiple elements and fires an error. i think the same issue is valid for other commands if yoi check it.

### Description of the Change

Closes #

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @username, @username2, ...

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Comment by aliaghdam** [comment]
Hi,
Why the CI workflows not runs automatically on pull-requests?

**Comment by jeffpaul** [comment]
@aliaghdam GitHub only runs for folks within the org, but I just set them to run now

**Comment by aliaghdam** [comment]
@jeffpaul please check the CI, it does not run.

**Comment by jeffpaul** [comment]
@aliaghdam it ran, just lots of E2E failures

**Comment by aliaghdam** [comment]
All are the same: 

SCR-20240626-rzc

**Review by faisal-alvi — APPROVED** [review]
@aliaghdam Thanks for the PR, code LGTM. The E2E tests are failing due to an unrelated issue that should be resolved in #126. It requires `wp-env` to be upgraded.

**Pull request merged**
